### PR TITLE
Fixed bug for linked question

### LINKED ISSUE #202: Bug with link question in create post

### PR DESCRIPTION
**Pull request by ong6**
Fixes #202

### CODE REVIEW

File: components/forms/CustomSingleSelect.tsx [hunk 1]
```diff
@@ -3,10 +3,12 @@ import Select from 'react-select'
 
 export default function CustomSingleSelect(props): JSX.Element {
   const [field, state, { setValue, setTouched }] = useField(props.field.name)
+  console.log(props)
```
Comment (tlylt) [inline components/forms/CustomSingleSelect.tsx:6]: forgot to remove log?

**Review by tlylt — APPROVED** [review]
LGTM, just a nit to fix

File: components/forms/CustomSingleSelect.tsx (hunk 1 above)
Comment (ong6) [reply components/forms/CustomSingleSelect.tsx:6]: yep
